# Generated by Django 4.1.10 on 2023-08-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password2',
            new_name='newpassword',
        ),
    ]
