# Generated by Django 4.1.10 on 2023-08-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_tasks_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='topshiriq_mavzu',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='topshiriq_nomer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='topshiriq_otdel',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='topshiriq_turi',
            field=models.CharField(max_length=50),
        ),
    ]
