# Generated by Django 4.1.10 on 2023-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_listtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOtdels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otdel_name', models.CharField(max_length=200)),
            ],
        ),
    ]
